// Auto-generated by ESP-PPQ quantize.py
// 模型: MobileNetV2 INT8
// 输入: [1, 3, 224, 224]
// 输出: [1, 2]
// 大小: 2410859 bytes (2354.4 KB)

#ifndef MODEL_DATA_H
#define MODEL_DATA_H

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

extern const uint8_t model_onnx_data[];
extern const unsigned int model_onnx_len;

#define MODEL_INPUT_NAME     "input"
#define MODEL_OUTPUT_NAME    "output"
#define MODEL_INPUT_SIZE     150528
#define MODEL_INPUT_WIDTH    224
#define MODEL_INPUT_HEIGHT   224
#define MODEL_INPUT_CHANNELS 3
#define MODEL_NUM_CLASSES    2
#define MODEL_LABEL_SCREW    0
#define MODEL_LABEL_WASHER   1

#ifdef __cplusplus
}
#endif

#endif // MODEL_DATA_H
